/* Independent visual prototype. No microphone, network, AI or system commands. */
const params = new URLSearchParams(location.search);
const concept = ['orbita','aurora','pulso'].includes(params.get('modelo')) ? params.get('modelo') : 'orbita';
const names = {orbita:'Órbita',aurora:'Aurora',pulso:'Pulso'};
const icons = {
 logo:'M4 16V8m4 12V4m4 13V7m4 13V4m4 12V8',
 home:'M3 10l9-7 9 7M5 9v11h5v-6h4v6h5V9',
 chat:'M20 11a8 8 0 0 1-8 8H5l-3 3v-9a9 9 0 0 1 18-2zM7 10h10M7 14h6',
 mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0V5zM5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8',
 screens:'M3 3h18v12H3zM12 15v5M8 20h8M6 7h5M6 10h8',
 flow:'M4 3h5v5H4zM15 16h5v5h-5zM6 8v8h9M9 5h8v11',
 memory:'M5 3h14v18H5zM8 7h8M8 11h6M8 15h7',
 spark:'M12 2l2.7 7.3L22 12l-7.3 2.7L12 22l-2.7-7.3L2 12l7.3-2.7L12 2z',
 settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8zM12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2',
 search:'M16 16l5 5M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14z',
 sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8zM12 1v3M12 20v3M1 12h3M20 12h3M4 4l2 2M18 18l2 2M4 20l2-2M18 6l2-2',
 moon:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11z',
 arrow:'M4 12h16M14 6l6 6-6 6',
 check:'M5 12l4 4L19 6',
 pause:'M8 5v14M16 5v14',
 play:'M7 4l13 8-13 8V4z',
 headphones:'M4 14v-3a8 8 0 0 1 16 0v3M4 12h4v8H4zM16 12h4v8h-4z',
 user:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8zM4 21v-2a8 8 0 0 1 16 0v2',
 bell:'M5 16V9a7 7 0 0 1 14 0v7l2 2H3l2-2zM10 21h4',
 flag:'M5 22V3M5 3h14l-3 5 3 5H5',
 folder:'M3 5h7l2 3h9v12H3V5z',
 close:'M5 5l14 14M5 19L19 5',
 menu:'M4 6h16M4 12h16M4 18h16',
 music:'M9 18V5l11-2v13M9 8l11-2M9 18a3 3 0 1 1-3-3c2 0 3 1 3 3zM20 16a3 3 0 1 1-3-3c2 0 3 1 3 3z',
 clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM12 7v5l4 2',
 phone:'M7 2h10v20H7zM11 18h2',
 bolt:'M13 2L4 14h7l-1 8 10-13h-7l0-7z',
 download:'M12 3v12M7 10l5 5 5-5M4 17v4h16v-4'
};
function icon(name){return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name]||icons.spark}"/></svg>`;}
function esc(text){return String(text).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));}
function read(key,fallback){try{return localStorage.getItem(key)||fallback;}catch{return fallback;}}
function save(key,value){try{localStorage.setItem(key,value);}catch{}}
let theme = params.get('tema') || read('mestre-design-'+concept,concept==='aurora'?'light':'dark');
if(!['dark','light'].includes(theme))theme='dark';
let current = 'home';
let paused = false;
let tabs = {voice:'Escuta',media:'Visão geral',flow:'Rotinas',memory:'Histórico',settings:'Aparência',evolve:'Testar versão'};
const menu = [
 ['home','home','Visão geral','Seu espaço','Central'],
 ['chat','chat','Conversa','Conversar','Conversa'],
 ['voice','mic','Voz e escuta','Sua voz','Áudio'],
 ['media','screens','Mídia e telas','Mídias e telas','Telas'],
 ['flow','flow','Rotinas','Seus rituais','Rotinas'],
 ['memory','memory','Memória','Lembranças','Registros'],
 ['evolve','spark','Evolução','Cuidar do Mestre','Revisão'],
 ['settings','settings','Ajustes','Personalizar','Sistema']
];
function label(page){const entry=menu.find(m=>m[0]===page);return entry[concept==='aurora'?3:concept==='pulso'?4:2];}
function nav(){return menu.map(([id,ico])=>`<button class="nav-item ${id===current?'active':''}" data-page="${id}" ${id===current?'aria-current="page"':''}>${icon(ico)}<span>${label(id)}</span></button>`).join('');}
function brand(){return `<a class="brand" href="?modelo=${concept}" aria-label="Mestre início"><span class="brand-mark">${icon('logo')}</span><span class="brand-text">mestre<span class="brand-sub">seu assistente pessoal</span></span></a>`;}
function searchButton(){return `<button class="search-btn" data-search>${icon('search')}<span>Buscar no Mestre</span><kbd>Ctrl K</kbd></button>`;}
function status(){return `<span class="status"><i class="dot"></i>${paused?'Escuta pausada':'Pronto para ouvir'} <span class="muted">· demo</span></span>`;}
function utilities(){return `<button class="icon-btn" data-theme aria-label="${theme==='dark'?'Ativar modo claro':'Ativar modo noturno'}">${icon(theme==='dark'?'sun':'moon')}</button><button class="icon-btn" data-feedback aria-label="Avaliar este modelo">${icon('flag')}</button>`;}
function wave(){return `<div class="wave" aria-hidden="true">${Array.from({length:33},(_,i)=>`<i style="--h:${12+Math.round((Math.sin(i*1.9)+1)*17+(Math.sin(i*.43)+1)*9)}px;--d:-${i*.15}s"></i>`).join('')}</div>`;}
function btn(text,action,ico='arrow',kind=''){return `<button class="btn ${kind}" ${action}>${text}${icon(ico)}</button>`;}
function head(title,desc,kicker='SEU ASSISTENTE. DO SEU JEITO.'){return `<div class="page-head"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${desc}</p></div><span class="tag">${icon('clock')}30 setembro · estudo visual</span></div>`;}
function voiceCard(){return `<section class="card voice-card"><div class="row"><h3>Uma palavra e estou aqui.</h3>${icon('mic')}</div>${wave()}<div class="row"><span class="status"><i class="dot"></i>${paused?'Pausado':'Escuta ativa'} · demo</span><span class="muted" style="font-size:10px">“Assessor”</span></div><p style="margin-top:11px">${paused?'Use Retomar para mudar o estado da demonstração.':'Visualização de exemplo. O microfone não é acessado.'}</p>${btn(paused?'Retomar escuta':'Pausar escuta','data-pause',paused?'play':'pause','ghost')}</section>`;}
function monitors(){return `<div class="monitor-grid">${[['01','YouTube','screens','Vídeo pausado','Esquerda'],['02','Disney+','play','Arthur Magnífico','Principal'],['03','Área de trabalho','folder','Livre','Direita']].map(([n,title,ico,note,pos])=>`<div class="monitor"><small>MONITOR ${n}</small><div class="screen">${icon(ico)}<span>${title}</span></div><div class="monitor-footer"><b>${pos}</b><span>${note}</span></div></div>`).join('')}</div>`;}
function activity(){return `<div class="activity-row">${icon('check')}<div>YouTube movido para a esquerda<small>Janela separada · monitor 1</small></div><time>agora</time></div><div class="activity-row">${icon('user')}<div>Perfil Arthur Magnífico escolhido<small>Disney+ · monitor principal</small></div><time>há 2 min</time></div><div class="activity-row">${icon('headphones')}<div>Escuta pronta para o próximo pedido<small>Exemplos de estados da interface</small></div><time>há 4 min</time></div>`;}
function quick(title,subtitle,ico,page){return `<button class="card quick" data-page="${page}"><span class="icon-tile">${icon(ico)}</span><span><strong>${title}</strong><small>${subtitle}</small></span>${icon('arrow')}</button>`;}
function home(){
 if(concept==='aurora')return `<div class="aurora-home">${head('Um pouco mais de leveza, Arthur.','Sua voz organiza o dia. Este espaço cuida do resto.','BEM-VINDO AO SEU ESPAÇO')}<div class="grid-two"><section class="card hero"><div class="hero-copy"><div class="eyebrow">SEU TEMPO, DE VOLTA</div><h2>O que vamos fazer<br>hoje, mestre?</h2><p>Uma conversa, sua música favorita ou tudo no lugar para começar.</p>${btn('Vamos conversar','data-page="chat"','arrow','primary')}</div><div class="petal-art" aria-hidden="true">${Array.from({length:8},(_,i)=>`<i style="--angle:${i*45}deg"></i>`).join('')}</div></section>${voiceCard()}</div>${auroraSpace()}<div class="section-label"><h2>Pequenos rituais. Um dia melhor.</h2><button class="text-btn" data-page="flow">Ver todos ${icon('arrow')}</button></div><div class="grid-two"><section class="card"><div class="ritual-list">${[['01','Hora de focar','Seus programas no lugar e o som na medida.','flow'],['02','Um intervalo merecido','Escolha o que ouvir ou retome sua série.','media'],['03','Deixar o Mestre melhor','Um teste por vez. Você conta o que aconteceu.','evolve']].map(([n,t,s,p])=>`<div class="ritual"><span>${n}</span><div><b>${t}</b><small>${s}</small></div><button class="icon-btn" data-page="${p}" aria-label="Abrir ${t}">${icon('arrow')}</button></div>`).join('')}</div></section><section class="card note-card"><div class="eyebrow">À SUA MANEIRA</div><h2>Seu universo de<br>música e histórias.</h2><p>Perfil demonstrativo: Arthur Magnífico.</p><div class="services"><span class="service-pill">YouTube</span><span class="service-pill">Disney+</span><span class="service-pill">Spotify</span></div><button class="text-btn" data-page="media">Abrir meu espaço de mídia ${icon('arrow')}</button></section></div></div>`;
 if(concept==='pulso')return `<div class="pulse-home">${head('Tudo sob seu comando.','Seu ambiente, suas telas e a próxima ação.','MESTRE / ESTAÇÃO PESSOAL')}<div class="metrics"><div class="metric"><span>Assistente</span><b>${paused?'Pausado':'Disponível'} <small class="muted">· demo</small></b></div><div class="metric"><span>Área de trabalho</span><b>03 monitores</b></div><div class="metric"><span>Próxima revisão</span><b>Interface</b></div><div class="metric"><span>Perfil de mídia</span><b>Arthur Magnífico</b></div></div><div class="grid-two"><div class="stack"><section class="card"><div class="card-top"><div><div class="eyebrow">MAPA DO AMBIENTE</div><h2 style="margin-top:6px">Cada janela no seu lugar.</h2></div><button class="icon-btn" data-page="media" aria-label="Organizar monitores">${icon('arrow')}</button></div>${monitors()}<div class="row between wrap" style="margin-top:22px"><span class="muted" style="font-size:11px">3 telas de exemplo · nenhum comando é executado</span>${btn('Organizar telas','data-page="media"','screens')}</div></section><section class="card pulse-command"><span class="eyebrow">COMANDO RÁPIDO</span><button class="search-btn" data-search><span>Busque uma ação ou configuração</span>${icon('search')}</button></section></div><div class="stack">${voiceCard()}<section class="card"><div class="card-top"><h3>Últimos movimentos</h3><span class="tag">demo</span></div>${activity()}</section></div></div><div class="section-label"><h2>Próxima ação</h2><span class="eyebrow">ACESSO DIRETO</span></div><div class="grid-three">${quick('Rotinas','Sequências sob controle','flow','flow')}${quick('Revisar versão','Roteiro guiado de teste','check','evolve')}${quick('Diagnóstico','Veja o estado dos recursos','bolt','settings')}</div></div>`;
 return `<div class="orbit-home">${head('Tudo pronto, Arthur.','Menos cliques. Mais espaço para o que importa.')}<div class="grid-two"><section class="card hero"><div class="hero-copy"><div class="eyebrow">A PRÓXIMA AÇÃO É SUA</div><h2>Seu mundo,<br>em sintonia.</h2><p>Converse, organize suas telas e retome o que você gosta.</p>${btn('Abrir conversa','data-page="chat"','arrow','primary')}</div><div class="orb" aria-hidden="true">${icon('logo')}</div></section>${voiceCard()}</div><div class="section-label"><h2>O que vamos fazer?</h2><span class="eyebrow">ATALHOS DO SEU DIA</span></div><div class="grid-three">${quick('Assistir & ouvir','Seu perfil, seus serviços','play','media')}${quick('Organizar meu dia','Rotinas e atalhos','flow','flow')}${quick('Testar atualização','Uma etapa por vez','check','evolve')}</div><div class="grid-two mt"><section class="card"><div class="card-top"><h3>Seu espaço, organizado</h3><button class="text-btn" data-page="media">Gerenciar ${icon('arrow')}</button></div>${monitors()}</section><section class="card"><div class="card-top"><h3>O que aconteceu</h3><span class="tag">exemplos</span></div>${activity()}</section></div></div>`;
}
function subnav(page,items){return `<nav class="subnav" aria-label="Seções de ${label(page)}">${items.map(t=>`<button class="btn ${tabs[page]===t?'selected':''}" data-tab="${t}" ${tabs[page]===t?'aria-current="page"':''}>${t}</button>`).join('')}</nav>`;}
function toggle(title,note,on=false){return `<div class="setting-row"><div><h3>${title}</h3><p>${note}</p></div><button class="switch" role="switch" aria-label="${title}" aria-checked="${on}" data-toggle></button></div>`;}
function savedemo(){return `<div class="savebar">${btn('Guardar ajustes da demonstração','data-demo="Ajustes demonstrados. A configuração do Mestre permanece a mesma."','check','primary')}</div>`;}
function voice(){const body=tabs.voice==='Escuta'?`<div class="grid-two"><section class="card"><div class="card-top"><h2>Eu te ouço melhor.</h2>${icon('mic')}</div><div class="setting-row"><div><h3>Microfone</h3><p>Escolha por onde sua voz chega.</p></div><select aria-label="Microfone de demonstração"><option>Microfone principal</option><option>Headset</option></select></div>${toggle('Ouvir só a minha voz','Ignorar outras pessoas e vídeos.',true)}<div class="setting-row"><div><h3>Sensibilidade</h3><p>Encontre o equilíbrio entre voz e ruído.</p></div><label><span class="range-value">60%</span><input type="range" min="0" max="100" value="60" aria-label="Sensibilidade" data-range></label></div><details><summary>Ajustes avançados de captação</summary><p>Pausa entre frases, ganho e espera pela palavra de ativação ficam aqui, sem ocupar a tela principal.</p></details>${savedemo()}</section>${voiceCard()}</div>`:tabs.voice==='Voz'?`<section class="card"><h2>Uma voz que combina com você.</h2><div class="setting-row"><div><h3>Motor de voz</h3><p>As opções já existentes continuam disponíveis.</p></div><select aria-label="Motor demonstrativo"><option>Kokoro · local</option> <option>Windows</option><option>Chatterbox · local</option></select></div><div class="setting-row"><div><h3>Velocidade</h3><p>De mais tranquila a mais rápida.</p></div><label><span class="range-value">50%</span><input type="range" value="50" aria-label="Velocidade" data-range></label></div>${toggle('Fala fluida','Ouvir uma resposta em partes.',true)}${savedemo()}</section>`:`<section class="card"><div class="empty-icon">${icon('user')}</div><h2>O Mestre reconhece você.</h2><p style="margin-top:12px">Cadastro e teste de reconhecimento ficam juntos. A demonstração não grava áudio.</p><div class="row mt wrap">${btn('Ver exemplo de cadastro','data-demo="No aplicativo: gravar frases e conferir a qualidade antes de salvar."','mic','primary')}${btn('Entender o reconhecimento','data-demo="O cadastro real é local; esta tela apenas demonstra a organização."','user')}</div></section>`;return head('Voz e escuta','Tudo para conversar com conforto e clareza.','AJUSTES DO ASSISTENTE')+subnav('voice',['Escuta','Voz','Meu reconhecimento'])+body;}
function media(){let tab=tabs.media;let body='';if(tab==='Visão geral'||tab==='Monitores')body=`<section class="card"><div class="card-top"><div><h2>Seu cinema. Suas telas.</h2><p style="margin-top:7px">Seleção explícita do serviço, perfil e destino.</p></div><span class="tag">3 telas · exemplo</span></div>${monitors()}<div class="row mt wrap"><label>Serviço<select id="demo-service"><option>YouTube</option><option>Disney+</option><option>Netflix</option><option>Prime Video</option></select></label><label>Destino<select id="demo-monitor"><option>Monitor 1 · esquerda</option><option>Monitor 2 · principal</option><option>Monitor 3 · direita</option></select></label>${btn('Visualizar organização','data-arrange','screens','primary')}</div></section>`;else if(tab==='Serviços')body=`<div class="grid-three service-grid">${['YouTube','Disney+','Netflix','Prime Video','Max','Spotify'].map(service=>`<section class="card service-card"><span class="service-logo">${service}</span><span class="profile-badge">${icon('user')}${service==='Spotify'?'Conta de demonstração':'Arthur Magnífico'}</span>${btn('Ver detalhes',`data-demo="${service}: aqui ficarão os perfis, canais ou playlists já configurados no Mestre."`,'arrow','ghost')}</section>`).join('')}</div>`;else body=`<section class="card"><h2>O lugar de cada aplicativo.</h2><div class="pill-rows mt">${['Navegador','Editor de código','Player de música'].map((t,i)=>`<div class="pill-row"><div><strong>${t}</strong><small>Destino e atalho de abertura</small></div><select aria-label="Monitor para ${t}"><option>Monitor ${i+1}</option><option>Monitor principal</option></select></div>`).join('')}</div>${savedemo()}</section>`;return head('Assistir, ouvir e organizar.','Serviços reunidos, com seu perfil sempre visível.','MÍDIA E TELAS')+subnav('media',['Visão geral','Serviços','Monitores','Programas e sites'])+body+`<div class="callout mt">${icon('user')}<div><strong>Arthur Magnífico</strong><p>Proposta de experiência: confirmar o perfil antes de perguntar o que você deseja assistir. O visual não altera a regra atual do programa.</p></div></div>`;}
function flow(){let tab=tabs.flow;return head('Um pedido. Tudo encaminhado.','Organize sequências, frases rápidas e projetos em um só lugar.','ROTINAS E ATALHOS')+subnav('flow',['Rotinas','Atalhos','Projetos'])+`<div class="grid-three">${(tab==='Rotinas'?[['Foco no trabalho','Abrir programas → organizar telas → iniciar música.','flow'],['Hora de relaxar','Escolher perfil → abrir streaming → perguntar o título.','play'],['Encerrar o dia','Reunir o que importa antes de descansar.','moon']]:tab==='Atalhos'?[['Abrir meu navegador','Uma frase curta para abrir um programa.','screens'],['Tocar minha playlist','Sua música com um pedido.','music'],['Ver meus lembretes','Suas anotações, no momento certo.','memory']]:[['Meus projetos','Planos e passos guiados já disponíveis.','folder'],['Notas do projeto','O que você quer guardar para depois.','memory'],['Próxima etapa','Uma ação clara para continuar.','arrow']]).map(([t,p,i])=>`<section class="card"><div class="empty-icon">${icon(i)}</div><h2>${t}</h2><p class="mt">${p}</p><div class="mt">${btn('Ver sequência',`data-demo="${t}: representação visual. Nenhuma rotina real será executada."`)}</div></section>`).join('')}</div><div class="callout mt">${icon('flow')}<div><strong>Exemplos para avaliar a organização</strong><p>Na implementação, os dados vêm das rotinas e atalhos existentes, sem criar ações novas automaticamente.</p></div></div>`;}
function memory(){return head('O que vale lembrar.','Seu histórico, suas notas e o contexto que você escolheu guardar.','MEMÓRIA')+subnav('memory',['Histórico','Lembranças','Desempenho'])+(tabs.memory==='Histórico'?`<section class="card"><div class="card-top"><h2>A história de cada pedido.</h2><span class="tag">dados fictícios</span></div>${activity()}<details><summary>Ver o que foi ouvido, entendido e executado</summary><p>Ouvi: “YouTube no monitor 1”. Entendi: mover a janela do YouTube. Fiz: janela movida para o monitor 1. Este é um exemplo visual.</p></details></section>`:tabs.memory==='Lembranças'?`<section class="card"><div class="empty-icon">${icon('memory')}</div><h2>Organizado por assunto.</h2><div class="services"><span class="service-pill">Preferências</span><span class="service-pill">Projetos</span><span class="service-pill">Anotações</span></div><p>Os assuntos e lembranças reais serão lidos da memória local existente.</p></section>`:`<section class="card"><h2>Onde o tempo é gasto.</h2><p class="mt">Sem inventar desempenho: quando não há medição, mostramos “sem dados”.</p><div class="stats-panel mt">${['Transcrever','Entender pedido','Pensar resposta','Começar a falar'].map(t=>`<div class="sample-stat"><span>${t}</span><b>—</b><span>Sem medição nesta demo</span></div>`).join('')}</div></section>`);}
const scenarios=[
 {id:'media-youtube',title:'Destino de uma janela',prepare:'Imagine o YouTube aberto e dois monitores disponíveis.',say:'Assessor, leva o YouTube para o monitor 1.',expect:'A janela do YouTube vai para o monitor 1. As outras janelas ficam onde estavam.'},
 {id:'profile',title:'Seu perfil de streaming',prepare:'Imagine uma plataforma na tela de escolha de perfil.',say:'Assessor, abre a Disney no perfil Arthur Magnífico.',expect:'O perfil solicitado é validado antes de continuar. Se houver dúvida, o assistente pergunta.'},
 {id:'ambiguity',title:'Uma pergunta antes de agir',prepare:'Imagine dois vídeos abertos em serviços diferentes.',say:'Assessor, pausa o vídeo.',expect:'Quando o alvo for ambíguo, o assistente pergunta qual vídeo você quer pausar.'},
 {id:'interrupt',title:'Interromper sem perder o controle',prepare:'No teste real, espere o assistente começar a responder.',say:'Assessor, para.',expect:'A fala para. Nenhum comando anterior é repetido.'},
 {id:'window',title:'Escolher o monitor',prepare:'Imagine uma janela em uma configuração de três monitores.',say:'Assessor, joga essa janela para outra tela.',expect:'Se não souber qual é o destino, o assistente pede que você escolha o monitor.'},
 {id:'question',title:'Uma pergunta de verdade',prepare:'Nenhum programa precisa estar aberto.',say:'Assessor, por que o céu muda de cor ao entardecer?',expect:'O assistente responde à pergunta, sem abrir um aplicativo ou executar uma rotina.'},
 {id:'audio',title:'Entender sua voz',prepare:'No teste real, fale num volume confortável.',say:'Assessor, qual é a data de hoje?',expect:'A resposta informa a data. O histórico mostra o pedido correto.'},
 {id:'complex',title:'Duas telas, dois destinos',prepare:'Imagine YouTube e Disney+ abertos.',say:'Assessor, YouTube no monitor 1 e Disney no monitor 3.',expect:'Cada destino é resolvido antes da execução. Se faltar informação, o assistente pergunta.'}
];
let testItems=[],testAnswers=[],testPosition=0;
function newRound(){const previous=testItems.map(x=>x.id).join();const pool=[...scenarios];for(let i=pool.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}testItems=pool.slice(0,4);if(testItems.map(x=>x.id).join()===previous)testItems=pool.slice(1,5);testPosition=0;testAnswers=[];}
newRound();
function validation(){let done=testPosition>=testItems.length,item=testItems[testPosition];return `<div class="test-layout"><section class="card test-stage"><div class="row between"><span class="eyebrow">${done?'ROTEIRO CONCLUÍDO':`ETAPA ${testPosition+1} DE ${testItems.length}`}</span><span class="tag">Simulação de interface</span></div><div class="progress" role="progressbar" aria-label="Etapas registradas" aria-valuenow="${testPosition}" aria-valuemin="0" aria-valuemax="${testItems.length}"><span style="width:${100*testPosition/testItems.length}%"></span></div>${done?`<div class="empty-icon">${icon('check')}</div><h2>Seu retorno está organizado.</h2><p class="mt">Você experimentou o fluxo de resposta. Estes registros não comprovam testes do Mestre.</p><div class="test-actions mt">${btn('Baixar demonstração','data-export-tests','download','primary')}${btn('Experimentar outra rodada','data-new-round','arrow')}</div>`:`<h3>${item.title}</h3><p class="mt"><strong>Antes:</strong> ${item.prepare}</p><div class="eyebrow mt">NO TESTE REAL, VOCÊ DIRIA</div><div class="say">“${item.say}”</div><div class="expected"><div class="eyebrow">O QUE VOCÊ DEVE CONFERIR</div><p>${item.expect}</p></div><label>Algo a registrar? <input type="text" id="test-note" placeholder="Ex.: não consegui escolher o monitor." maxlength="500"></label><div class="test-actions mt">${btn('Funcionou','data-result="pass"','check','primary')}${btn('Deu problema','data-result="fail"','flag')}${btn('Não consegui testar','data-result="skip"','arrow','ghost')}</div><details><summary>Detalhes técnicos e evidências</summary><p>Na versão real: vincular transcrição, ação e identificador desta etapa. Nesta demo nenhuma fala é capturada.</p></details>`}</section><aside class="stack" style="align-content:start"><section class="card"><h3>Você só precisa observar.</h3><p class="mt">Uma instrução por vez, resultado esperado em português e espaço para contar o que aconteceu.</p><div class="step-summary"><span>Funcionou</span><b>${testAnswers.filter(x=>x.result==='pass').length}</b></div><div class="step-summary"><span>Precisa de ajuste</span><b>${testAnswers.filter(x=>x.result==='fail').length}</b></div><div class="step-summary"><span>Não testado</span><b>${testAnswers.filter(x=>x.result==='skip').length}</b></div><p class="small-note">Sem repetir a mesma sequência: este protótipo alterna exemplos de um conjunto local.</p></section><section class="card"><div class="eyebrow">NA IMPLEMENTAÇÃO</div><p class="mt">O roteiro virá das mudanças reais da versão, das falhas recentes e de testes essenciais. Sorteio sozinho não define cobertura.</p><button class="text-btn mt" data-new-round>Ver outra rodada ${icon('arrow')}</button></section></aside></div>`;}
function evolve(){return head('Melhor a cada retorno.','Uma observação clara vale mais do que um relatório confuso.','EVOLUÇÃO')+subnav('evolve',['Testar versão','Ideias','Sugestões'])+(tabs.evolve==='Testar versão'?validation():`<section class="card"><div class="empty-icon">${icon('spark')}</div><h2>${tabs.evolve==='Ideias'?'Seu próximo “e se…”.':'Oportunidades, sem ruído.'}</h2><p class="mt">Ideias e sugestões ficam separadas dos erros encontrados. O envio para a IA é uma ação explícita.</p><div class="mt">${btn('Registrar opinião sobre o layout','data-feedback','flag','primary')}</div></section>`);}
function settings(){let b=tabs.settings==='Aparência'?`<section class="card"><h2>Seu espaço também tem seu jeito.</h2><div class="setting-row"><div><h3>Modo ${theme==='dark'?'noturno':'claro'}</h3><p>A mesma estrutura, com contraste apropriado.</p></div>${btn('Trocar tema','data-theme',theme==='dark'?'sun':'moon')}</div><div class="setting-row"><div><h3>Tipografia desta proposta</h3><p>${concept==='aurora'?'Georgia nos títulos · Segoe UI na leitura':concept==='pulso'?'Bahnschrift nos títulos · Consolas em dados · Segoe UI nos textos':'Segoe UI · hierarquia por peso, tamanho e espaço'}</p></div><span class="tag">Fontes locais</span></div>${toggle('Animações suaves','Respeita a preferência do sistema por movimento reduzido.',true)}<div class="savebar">${btn('Avaliar este modelo','data-feedback','flag','primary')}</div></section>`:tabs.settings==='Personalidade'?`<section class="card"><h2>Do seu jeito de conversar.</h2><div class="grid-two mt"><label>Nome do assistente<input type="text" value="Assessor"></label><label>Como ele chama você<input type="text" value="Mestre"></label></div><div class="setting-row"><div><h3>Estilo de conversa</h3><p>As personalidades existentes serão preservadas.</p></div><select aria-label="Estilo"><option>Direto e gentil</option><option>Descontraído</option><option>Objetivo</option></select></div>${savedemo()}</section>`:tabs.settings==='Conexões'?`<section class="card"><h2>Por perto, mesmo no celular.</h2><div class="setting-row"><div><h3>Celular e Telegram</h3><p>O acesso à configuração atual fica neste espaço.</p></div><span class="tag">Demonstração</span></div><p>Credenciais continuam fora do projeto. Nenhuma conexão é feita nesta prévia.</p></section>`:`<section class="card"><h2>Um diagnóstico que dá para entender.</h2><div class="pill-rows mt">${['Painel','Microfone','Extensão do navegador','IA local'].map(t=>`<div class="pill-row"><strong>${t}</strong><span class="tag">Não medido · demo</span></div>`).join('')}</div></section>`;return head('Ajustes, sem complicação.','O essencial aparece primeiro. O avançado fica ao alcance.','PERSONALIZAÇÃO')+subnav('settings',['Aparência','Personalidade','Conexões','Diagnóstico'])+b;}
function chat(){return head('Pode falar, Arthur.','Conversa e ação no mesmo lugar, com o contexto sempre visível.','CONVERSA')+`<div class="grid-two"><section class="card"><div id="chat-messages" class="chat-demo"><div class="bubble user-bubble">Quero assistir alguma coisa na Disney.</div><div class="bubble">Vamos usar o perfil <strong>Arthur Magnífico</strong>? Depois me diga o que deseja assistir.</div><div class="bubble user-bubble">Isso. No monitor principal.</div><div class="bubble">Entendido. Esta é uma conversa de exemplo para avaliar a nova tela.</div></div><form id="chat-form" class="chat-input"><input type="text" aria-label="Mensagem de demonstração" placeholder="Experimente escrever uma mensagem…" maxlength="400" required>${btn('Enviar exemplo','type="submit"','arrow','primary')}</form></section><div class="stack" style="align-content:start">${voiceCard()}<section class="card"><h3>Contexto à vista</h3><div class="step-summary"><span>Perfil</span><b>Arthur Magnífico</b></div><div class="step-summary"><span>Destino</span><b>Monitor principal</b></div><p class="small-note">A conversa é simulada. Nenhuma IA será consultada.</p></section></div></div>`;}
function render(){document.body.dataset.concept=concept;document.body.dataset.theme=theme;document.documentElement.style.colorScheme=theme==='dark'?'dark':'light';document.title=`Mestre · ${names[concept]} · ${label(current)}`;document.querySelector('#concept-name').textContent=names[concept];document.querySelectorAll('.lab nav a').forEach(a=>{if(a.href.includes('modelo='+concept))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});let content=({home,voice,media,flow,memory,evolve,settings,chat}[current])();let inside=`<main class="content" id="content" tabindex="-1">${content}<footer class="footer-note"><span>Mestre · ${names[concept]} / protótipo navegável</span><span>Dados ilustrativos · funciona localmente · sem captura de áudio</span></footer></main>`;document.querySelector('#shell').innerHTML=concept==='aurora'?`<div class="shell aurora-shell ${paused?'is-paused':''}"><header class="aurora-header"><div class="aurora-top">${brand()}<div class="row">${status()}${searchButton()}${utilities()}</div></div><nav class="top-nav" aria-label="Navegação principal">${nav()}</nav></header>${inside}</div>`:`<div class="shell ${concept==='pulso'?'pulse-shell':''} ${paused?'is-paused':''}"><aside class="sidebar">${brand()}<nav class="nav-group" aria-label="Navegação principal"><span class="eyebrow">SEU ESPAÇO</span>${nav()}</nav><div class="sidebar-footer"><button class="nav-item" data-feedback>${icon('flag')}<span>Avaliar proposta</span></button><div class="user"><span class="avatar">AM</span><div><strong>Arthur Magnífico</strong><small>Espaço pessoal</small></div></div></div></aside><div class="workspace"><header class="toolbar"><button class="icon-btn mobile-menu" data-menu aria-label="Abrir menu">${icon('menu')}</button><span class="breadcrumb">Meu espaço / <span style="color:var(--text)">${label(current)}</span></span><span class="toolbar-spacer"></span>${searchButton()}${utilities()}</header>${inside}</div></div>`;}
function navigate(page){if(!menu.some(m=>m[0]===page))return;current=page;render();window.scrollTo(0,0);document.querySelector('#content').focus({preventScroll:true});}
let toastTimer;function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4200);}
const keywords={home:'início principal dashboard',chat:'conversa ia resposta',voice:'microfone voz áudio ganho sensibilidade reconhecimento kokoro',media:'youtube disney netflix spotify prime max monitores telas programas sites perfil',flow:'rotinas atalhos projetos sequências',memory:'histórico memória lembranças notas tempos desempenho',evolve:'validar testes atualização melhorias sugestões feedback',settings:'aparência tema fontes personalidade celular telegram conexões diagnóstico'};
function search(){const dialog=document.querySelector('#search-dialog');dialog.showModal();document.querySelector('#search-input').value='';searchResults('');document.querySelector('#search-input').focus();}
function searchResults(query){const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const matches=menu.filter(m=>norm(label(m[0])+' '+keywords[m[0]]).includes(norm(query)));document.querySelector('#search-results').innerHTML=matches.length?matches.map(([p,i])=>`<button class="search-result" data-page="${p}">${icon(i)}<span>${label(p)}</span></button>`).join(''):'<p>Nada encontrado. Tente “voz”, “telas” ou “testes”.</p>';}
function download(filename,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
document.addEventListener('click',event=>{const el=event.target.closest('button');if(!el)return;if(el.hasAttribute('data-page')){document.querySelectorAll('dialog[open]').forEach(d=>d.close());navigate(el.dataset.page);}else if(el.hasAttribute('data-tab')){tabs[current]=el.dataset.tab;render();}else if(el.hasAttribute('data-theme')){theme=theme==='dark'?'light':'dark';save('mestre-design-'+concept,theme);render();}else if(el.hasAttribute('data-pause')){paused=!paused;render();toast(paused?'Demonstração pausada. Nenhum microfone real foi alterado.':'Demonstração retomada.');}else if(el.hasAttribute('data-search'))search();else if(el.hasAttribute('data-close'))el.closest('dialog').close();else if(el.hasAttribute('data-feedback'))document.querySelector('#feedback-dialog').showModal();else if(el.hasAttribute('data-menu')){document.querySelector('.shell').classList.toggle('menu-open');}else if(el.hasAttribute('data-toggle')){const checked=el.getAttribute('aria-checked')!=='true';el.setAttribute('aria-checked',String(checked));if(el.getAttribute('aria-label')==='Animações suaves')document.querySelectorAll('.wave i').forEach(i=>i.style.animationPlayState=checked?'running':'paused');toast('Preferência demonstrada nesta tela.');}else if(el.hasAttribute('data-demo'))toast(el.dataset.demo);else if(el.hasAttribute('data-arrange')){toast(`Prévia: ${document.querySelector('#demo-service').value} → ${document.querySelector('#demo-monitor').value}. Nenhuma janela real foi movida.`);}else if(el.hasAttribute('data-result')&&testPosition<testItems.length){testAnswers.push({id:testItems[testPosition].id,result:el.dataset.result,note:document.querySelector('#test-note').value});testPosition++;render();}else if(el.hasAttribute('data-new-round')){newRound();render();toast('Nova rodada de exemplos preparada.');}else if(el.hasAttribute('data-export-tests'))download('DEMONSTRACAO-layout-'+concept+'.json',JSON.stringify({tipo:'simulacao_de_interface_nao_validacao_real',modelo:concept,respostas:testAnswers},null,2),'application/json');});
document.addEventListener('input',event=>{if(event.target.id==='search-input')searchResults(event.target.value);if(event.target.hasAttribute('data-range'))event.target.previousElementSibling.textContent=event.target.value+'%';});
document.addEventListener('submit',event=>{if(event.target.id==='chat-form'){event.preventDefault();const input=event.target.querySelector('input');const text=input.value.trim();if(!text)return;const messages=document.querySelector('#chat-messages');let mine=document.createElement('div');mine.className='bubble user-bubble';mine.textContent=text;messages.append(mine);let response=document.createElement('div');response.className='bubble';response.textContent='Mensagem recebida nesta demonstração. Na versão integrada, o motor atual do Mestre responderá aqui.';messages.append(response);input.value='';}if(event.target.id==='feedback-form'){event.preventDefault();let form=new FormData(event.target);let liked=String(form.get('liked')).trim();if(!liked)return;let change=String(form.get('change')).trim();let summary=`# Preferência de layout — Mestre\n\nModelo: ${names[concept]}\nTema: ${theme==='dark'?'noturno':'claro'}\n\nGostei: ${liked}\n\nMudaria: ${change||'Nada registrado.'}\n\nEsta preferência deve ser confirmada no chat. Não é publicação nem implementação automática.\n`;save('mestre-layout-preferencia',summary);download('preferencia-layout-mestre.md',summary);document.querySelector('#feedback-dialog').close();toast('Preferência guardada neste navegador e enviada para download.');}});
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();if(!document.querySelector('dialog[open]'))search();}if(event.key==='Escape')document.querySelector('.shell')?.classList.remove('menu-open');});
function auroraSpace(){return `<section class="card aurora-space"><div class="card-top"><div><div class="eyebrow">MÍDIAS E TELAS</div><h2>Seu espaço, organizado</h2><p style="margin-top:7px">Veja serviços, perfis e o destino de cada janela em um só lugar.</p></div><button class="text-btn" data-page="media">Abrir detalhes ${icon('arrow')}</button></div>${monitors()}<div class="row between wrap" style="margin-top:18px"><div class="services"><span class="service-pill">Arthur Magnífico</span><span class="service-pill">YouTube</span><span class="service-pill">Disney+</span><span class="service-pill">Spotify</span></div><span class="small-note">Demonstração · nenhuma janela real é movida</span></div></section>`;}
render();
